name: podfile_modifier
description: A Dart package to modify the Podfile for Flutter projects.
version: 0.1.0
homepage: https://github.com/classycircle/podfile_modifier

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  podfile_modifier: main
